src/objects/Formulary_Association__c.object
<CustomObject>
    <fields>
        <fullName>Covered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Covered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Formulary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Formulary</label>
        <referenceTo>My_Formulary__c</referenceTo>
        <relationshipLabel>Formulary Associations</relationshipLabel>
        <relationshipName>Formulary_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insured_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Insured Item</label>
        <referenceTo>Insured_Item__c</referenceTo>
        <relationshipLabel>Formulary Associations</relationshipLabel>
        <relationshipName>Formulary_Associations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Formulary Association</label>
    <nameField>
        <label>Formulary Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Formulary Associations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Insured_Item__c.object
<CustomObject>
    <fields>
        <fullName>Dosage_Form__c</fullName>
        <label>Dosage Form</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>TABLET, FILM COATED</fullName>
                </value>
                <value>
                    <fullName>TABLET</fullName>
                </value>
                <value>
                    <fullName>GRANULE, DELAYED RELEASE</fullName>
                </value>
                <value>
                    <fullName>INJECTION, SOLUTION</fullName>
                </value>
                <value>
                    <fullName>CAPSULE</fullName>
                </value>
                <value>
                    <fullName>AEROSOL, METERED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Drug_Coverage_Status_Code__c</fullName>
        <label>Drug Coverage Status Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
                <value>
                    <fullName>O</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_NDC__c</fullName>
        <label>Product NDC</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Route__c</fullName>
        <label>Route</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ORAL</fullName>
                </value>
                <value>
                    <fullName>SUBCUTANEOUS</fullName>
                </value>
                <value>
                    <fullName>ORAL; RESPIRATORY (INHALATION)</fullName>
                </value>
                <value>
                    <fullName>RESPIRATORY (INHALATION)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Substance_Name__c</fullName>
        <label>Substance Name</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>Insured Item</label>
    <nameField>
        <label>Proprietary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insured Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/My_Formulary__c.object
<CustomObject>
    <fields>
        <fullName>Coverage_End_Date__c</fullName>
        <label>Coverage End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Coverage_Start_Date__c</fullName>
        <label>Coverage Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <label>Group Number</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Health_Plan__c</fullName>
        <label>Health Plan</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_ID__c</fullName>
        <label>Member ID</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Name__c</fullName>
        <label>PCP Name</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCP_Phone__c</fullName>
        <label>PCP Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Payer_ID__c</fullName>
        <label>Payer ID</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <label>My Formulary</label>
    <nameField>
        <label>Insurance Provider</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Formularies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/My_Prescription__c.object
<CustomObject>
    <fields>
        <fullName>Covered__c</fullName>
        <formula>IF( Formulary_Association__r.Covered__c = TRUE, IMAGE(&quot;/resource/greenCircle&quot;, &quot;COVERED)&quot;, 25,25), IMAGE(&quot;/resource/redCircle&quot;, &quot;NOT COVERED&quot;, 25,25))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is It Covered?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Formulary_Association__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Formulary Association</label>
        <referenceTo>Formulary_Association__c</referenceTo>
        <relationshipLabel>Formulary Association</relationshipLabel>
        <relationshipName>Formulary_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>My_Insurance__c</fullName>
        <label>My Insurance</label>
        <referenceTo>My_Formulary__c</referenceTo>
        <relationshipLabel>My Prescriptions (My Insurance)</relationshipLabel>
        <relationshipName>My_Prescriptions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Pharmacy__c</fullName>
        <label>Pharmacy</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pill_Counter__c</fullName>
        <label>Number of Pills in Current Prescription</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pills_Taken__c</fullName>
        <label>Number of Pills Taken</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RX_Number__c</fullName>
        <label>RX Number</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Take_with_Food__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Required to Take with Food</label>
        <type>Checkbox</type>
    </fields>
    <label>My Prescription</label>
    <nameField>
        <displayFormat>RX-{000000}</displayFormat>
        <label>Prescription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Prescriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pill__c.object
<CustomObject>
    <fields>
        <fullName>My_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>My Prescription?</label>
        <referenceTo>My_Prescription__c</referenceTo>
        <relationshipLabel>Pills Identifier</relationshipLabel>
        <relationshipName>Pills_Identifier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Predicted_Drug_Name__c</fullName>
        <label>Predicted Drug Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ethinylestradiol</fullName>
                </value>
                <value>
                    <fullName>Lorazepam</fullName>
                </value>
                <value>
                    <fullName>Oxybutynin</fullName>
                </value>
                <value>
                    <fullName>NOT AVAILABLE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pill Identifier</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Pill Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pills Identifier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestHelper.cls
public with sharing class TestHelper  {

    public String uniqueStr;

    // constructor
    public TestHelper(String x_uniqueStr) {
        this.uniqueStr = x_uniqueStr;
    }

    // didn't automake user because it has to be done in a different context
    public User adminUser {get;set;}

    // this is the lazy pattern
    public My_Formulary__c myFormulary {get {
        if(this.myFormulary == null) this.createMyFormulary();
        return myFormulary;
    } set;}
    public Formulary_Association__c formularyAssn {get {
        if(this.formularyAssn == null) this.createFormularyAssn();
        return formularyAssn;
    } set;}
    public Insured_Item__c insuredItem {get {
        if(this.insuredItem == null) this.createInsuredItem();
        return insuredItem;
    } set;}
    public My_Prescription__c myRx {get{
        if(this.myRx == null) this.createMyRx();
        return myRx;
    } set;}
    public Pill__c pill {get{
        if(pill == null) this.createPill();
        return this.pill;
    } set;}
    public Event pillTaken {get{
        if(pillTaken == null) this.takePill();
        return pillTaken;
    } set;}

    public TestHelper createAdminUser() {
        Profile p = [SELECT Id FROM profile WHERE name='System Administrator' LIMIT 1];
        String x_emailPrefix = this.uniqueStr + 'email';
        String x_alias = x_emailPrefix.length() > 8 ? x_emailPrefix.subString(x_emailPrefix.length() - 8,x_emailPrefix.length()) : x_emailPrefix;
        adminUser = new User(
            alias = x_alias,
            email = x_emailPrefix + '=test.com@example.com',
            emailencodingkey = 'UTF-8', 
            lastname = this.uniqueStr, 
            languagelocalekey = 'en_US',
            localesidkey = 'en_US', 
            profileid = p.Id,
            timezonesidkey = 'America/Chicago',
            username = x_emailPrefix+'=test.com@example.com.testing'
        );
        insert this.adminUser;
        return this;
    }

    public TestHelper createInsuredItem() {
        insuredItem = new Insured_Item__c(
            Substance_Name__c = 'Lorazepam',
            Route__c = 'ORAL',
            Name = 'Lorazepam',
            Product_NDC__c = 'abc123',
            Drug_Coverage_Status_Code__c = 'C',
            Dosage_Form__c = 'TABLET'
        );
        insert this.insuredItem;
        return this;
    }

    public TestHelper createMyFormulary() {
        myFormulary = new My_Formulary__c(
            Coverage_Start_Date__c = Date.today().addDays(-180),
            Coverage_End_Date__c = Date.today().addDays(180),
            Group_Number__c = 'abc123',
            Health_Plan__c = 'abc123',
            Name = 'United Healthcare',
            Member_ID__c = 'abc123',
            OwnerId = adminUser.Id,
            Payer_ID__c = 'abc123',
            PCP_Name__c = 'United Healthcare',
            PCP_Phone__c = 'abc123'
        );
        insert this.myFormulary;
        return this;
    }

    public TestHelper createFormularyAssn() {
        this.formularyAssn = new Formulary_Association__c(
            Covered__c = true,
            Formulary__c = this.myFormulary.Id,
            Insured_Item__c = this.insuredItem.Id
        );
        insert this.formularyAssn;
        return this;
    }

    public TestHelper createMyRx() {
        this.myRx = new My_Prescription__c(
            Formulary_Association__c = this.formularyAssn.Id,
            My_Insurance__c = this.myFormulary.Id,
            Pill_Counter__c = 30,
            Pills_Taken__c = 0,
            Pharmacy__c = this.uniqueStr,
            Take_with_Food__c = true,
            RX_Number__c = 'RX-' + uniqueStr 
        );
        insert this.myRx;
        return this;
    }

    public TestHelper createPill() {
        this.pill = new Pill__c(
            OwnerId = this.adminUser.Id,
            Predicted_Drug_Name__c = 'Lorazepam'
        );
        insert this.pill;
        return this;
    }

    public TestHelper takePill() {
        pillTaken = new Event(
            OwnerId = this.adminUser.Id,
            WhatId = this.myRx.Id,
            Subject = 'Take Pill',
            Pill_Number__c = 1,
            Took_with_Food__c = true,
            ActivityDateTime = DateTime.now(),
            DurationInMinutes = 15
        );
        insert pillTaken;
        return this;
    }
}