src/objects/My_Prescription__c.object
<CustomObject>
    <fields>
        <fullName>Finding_Prescription_Filter__c</fullName>
        <description>Filter for query. Medication name should be lowercase</description>
        <formula>CASESAFEID(Formulary_Association__r.OwnerId) + LOWER(Formulary_Association__r.Insured_Item__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This is simply a filter used to query the owner and the drug name</inlineHelpText>
        <label>Finding Prescription Filter</label>
        <type>Text</type>
    </fields>
    <label>My Prescription</label>
    <nameField>
        <displayFormat>RX-{000000}</displayFormat>
        <label>Prescription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Prescriptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Pill__c.object
<CustomObject>
    <fields>
        <fullName>My_Prescription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>My Prescription?</label>
        <referenceTo>My_Prescription__c</referenceTo>
        <relationshipLabel>Pills Identifier</relationshipLabel>
        <relationshipName>Pills_Identifier</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Predicted_Drug_Name__c</fullName>
        <label>Predicted Drug Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ethinylestradiol</fullName>
                </value>
                <value>
                    <fullName>Lorazepam</fullName>
                </value>
                <value>
                    <fullName>Oxybutynin</fullName>
                </value>
                <value>
                    <fullName>NOT AVAILABLE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pill Identifier</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Pill Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pills Identifier</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Pill_TH.cls
// Pill Identifier (Pill__c) trigger handler
public with sharing class Pill_TH  {

    public static void beforeInsert(List<Pill__c> newTrigger) {
        doPrescriptionLookup(newTrigger);
    }

    public static void beforeUpdate(List<Pill__c> newTrigger, Map<Id, Pill__c> oldTrigger) {
        // the logic only needs to runs if something important has changed
        List<Pill__c> changedPills = new List<Pill__c>();

        // loop through trigger items
        for(Pill__c pill:newTrigger) {
            // if something important has changed
            if(pill.Predicted_Drug_Name__c != oldTrigger.get(pill.Id).Predicted_Drug_Name__c || pill.OwnerId != oldTrigger.get(pill.Id).OwnerId) {
                // add the pill to the list
                changedPills.add(pill);
            }
        }

        // if there are pills in the list
        if(changedPills != null && !changedPills.isEmpty()) {
            // do the prescription look up on the list
            doPrescriptionLookup(changedPills);
        }
    }

    public static void doPrescriptionLookup(List<Pill__c> pills) {

        // using this kind of map means you only have to use two loops
        // the key matches the Finding_Prescription_Filter__c formula field
        Map<String,List<Pill__c>> pillMap = new Map<String,List<Pill__c>>();

        // makes the code run faster with less memory
        String key;

        // build the pill map
        for(Pill__c pill:pills) {

            // build the key
            key = pill.OwnerId;
            if (String.isNotBlank(pill.Predicted_Drug_Name__c))
            {
                key = key + pill.Predicted_Drug_Name__c.toLowerCase();
            }
            System.debug('Pill Key is ' + key);

            // if the key is in the map, add the pill to the list
            if(pillMap.containsKey(key)) pillMap.get(key).add(pill);
            else pillMap.put(key, new List<Pill__c>{pill});
        }

        // loop through the query results
        for(My_Prescription__c mp:[
            SELECT  Id, Finding_Prescription_Filter__c
            FROM    My_Prescription__c 
            WHERE   Finding_Prescription_Filter__c IN :pillMap.keySet()
            AND     Finding_Prescription_Filter__c != null
            AND     Finding_Prescription_Filter__c != ''
        ]) {
            key = mp.Finding_Prescription_Filter__c;
            // it should exist
            if(pillMap.containsKey(key)) {
                // loop through the pills under this key
                for(Pill__c pill:pillMap.get(key)) {
                    // assign the correct prescription ID
                    pill.My_Prescription__c = mp.Id;
                }
            }
        }
    }
}

/*
I was a working journalist, a hired geek of sorts, and Lazlo was great copy and 
sometimes a great lawyer. It was a fast, strange time and we worked in a fast, 
strange ways.
*/